@startuml

interface IEmailVerificationRequest {
    username: string
    confirmationCode: number
}

interface IImage {
    srcUrl: string
}

interface IBaseIngredient {
    id: number
    name: string
    category: string
}

interface IIngredientQuantity {
    quantity: IUnit
    quantityUnits: sring[]
}

interface IIngredient extends IBaseIngredient, IIngredientQuantity {
    nutrients?: INutrient[]
}

interface IInventoryIngredient extends IBaseIngredient {
    expirationDate: number | null
}

interface IShoppinIngredient extends IBaseIngredient, IIngredientQuantity {
    itemID?: string
    recipeID?: number
}

interface IInstruction {
    instructions: string
    ingredients: IIngredient[]
}

interface INutrient {
    name: string
    unit: IUnit
    percentOfDaily: number
}

interface IBaseRecipe {
    id: number
    name: string
    image: IImage
    ingredients: IIngredient
}

interface IRecipe extends IBaseRecipe {
    cuisines: string[]
    diets: string[]
    mealTypes: string[]
    instruction: IInstruction
    nutritionFacts: INutrient[]
    instructionSteps: IInstruction[]
    servings: number
    cookingTimeInMinutes: number
    preparationTimeInMinutes: number
    totalCost: number
    costPerServing: number
}

interface IUserRecipe extends IRecipe {
    isFavorite: boolean
    hasAllergens: boolean
}

interface IUserBaseRecipe extends IBaseRecipe {
    isFavorite: boolean
    hasAllergens: boolean
}

class Token {
    accessToken: string
    refreshToken: string
}

interface IUnit {
    unit: string
    value: number
}

interface IBaseUser {
    firstName: string
    lastName: string
    lastSeen: number
}

interface IContactInformation {
    email: string
}

interface ICredentials extends IIdentification {
    password: string
}

interface IIdentification {
    username: string
}

interface IUser extends IBaseUser, ICredentials, IContactInformation {
    isVerified: boolean
    profilePicture: IImage
    inventory: IInventoryIngredient[]
    shoppingList: IShoppinIngredient[]
    allergens: IBaseIngredient[]
    favoriteRecipes: IBaseRecipe[]
}

@enduml
